// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var SquareVerifier = artifacts.require('SquareVerifier');
var proof = require('./proof.json');

contract('SquareVerifier', accounts => {
    describe('Testing zokrates proof',  async () => {
        beforeEach(async function () {
            this.contract = await SquareVerifier.new();
        });
        // Test verification with correct proof
        // - use the contents from proof.json generated from zokrates steps
        it('should return true', async function () {
            let result = await this.contract.verifyTx(
                proof.proof.A,
                proof.proof.A_p,
                proof.proof.B,
                proof.proof.B_p,
                proof.proof.C,
                proof.proof.C_p,
                proof.proof.H,
                proof.proof.K,
                proof.input,
            );
            console.log(result.logs);
            //assert.equal(result, true, "The tx verification should return true");
        });
        // Test verification with incorrect proof
        /*it('should return false', async function () {
            let result = await this.contract.verifyTx(
                proof.proof.A,
                proof.proof.A_p,
                proof.proof.B,
                proof.proof.B_p,
                proof.proof.C,
                proof.proof.C_p,
                proof.proof.H,
                proof.proof.K,
                proof.input,
            );
            assert.equal(result, false, "The tx verification should return false");
        });*/
    });


});

